#!/bin/bash

# Ce script verifie si le système utilise apt or yum, puis installe git avec lles commandes addaptées

if command -v apt >/dev/null; then
  apt update
  apt install -y git-all
elif command -v yum >/dev/null; then
  yum check-update
  yum install -y git
else
  echo "Ni apt ni yuml ne sont disponible sur votre système : veuillez consulter votre administrateur"
fi

